branch-defaults:
  default:
    environment: avajams-env
global:
  application_name: avajams
  default_ec2_keyname: temp_hackathon_ai.pem
  default_platform: Docker 1.11.1
  default_region: us-east-1
  profile: null
  sc: null
